// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdl0e_eicGAlzoBxLwC7K3NoxJUEgnH_g',
    appId: '1:386692353743:web:d3c4d715b8e45c1d04f1ba',
    messagingSenderId: '386692353743',
    projectId: 'merkado-cfaa7',
    authDomain: 'merkado-cfaa7.firebaseapp.com',
    storageBucket: 'merkado-cfaa7.appspot.com',
    measurementId: 'G-B365JZVF9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_JVEXL6cLkdg8SHHeSv46MwfXygNluPY',
    appId: '1:386692353743:android:016a59a6abd4bdf204f1ba',
    messagingSenderId: '386692353743',
    projectId: 'merkado-cfaa7',
    storageBucket: 'merkado-cfaa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_K3Nt6EDIUwcu5obfyb-HcB8C35m0Is',
    appId: '1:386692353743:ios:acd55b64d69d6d1d04f1ba',
    messagingSenderId: '386692353743',
    projectId: 'merkado-cfaa7',
    storageBucket: 'merkado-cfaa7.appspot.com',
    iosClientId:
        '386692353743-n8jumeavggqd1pt4ipeuh31tnb0ltc3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.merkado',
  );
}
